// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    'IconParkOutline:abdominal': typeof import('virtual:vite-icons/icon-park-outline/abdominal')['default']
    'IconParkOutline:arrowKeys': typeof import('virtual:vite-icons/icon-park-outline/arrow-keys')['default']
    'IconParkOutline:bringForward': typeof import('virtual:vite-icons/icon-park-outline/bring-forward')['default']
    'IconParkOutline:colorFilter': typeof import('virtual:vite-icons/icon-park-outline/color-filter')['default']
    'IconParkOutline:paperMoneyTwo': typeof import('virtual:vite-icons/icon-park-outline/paper-money-two')['default']
    'IconParkOutline:shoppingCartOne': typeof import('virtual:vite-icons/icon-park-outline/shopping-cart-one')['default']
    README: typeof import('./src/components/README.md')['default']
  }
}

export { }
